/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useLayoutEffect, useMemo } from 'react';
import { useGLTF } from '@react-three/drei';
import * as THREE from 'three';

const ESCAVATOR_MODEL_PATH = '/objects/escavator.glb';

export function Escavator(props) {
    const gltf = useGLTF(ESCAVATOR_MODEL_PATH);
    const scene = useMemo(() => gltf.scene.clone(true), [gltf.scene]);
    const ref = useRef();

    useLayoutEffect(() => {
        scene.traverse((child) => {
            if (child.isMesh) {
                child.castShadow = true;
                child.receiveShadow = true;
                if (child.material) {
                    child.material.envMapIntensity = 1;
                    child.material.transparent = false;
                    child.material.opacity = 1;
                    child.material.side = THREE.DoubleSide;
                }
            }
        });
    }, [scene]);

    return (
        <group {...props} dispose={null} ref={ref}>
            <primitive object={scene} scale={1.8} position={[0, 0, 0]} rotation={[0, -Math.PI / 4, 0]} />
        </group>
    );
}

useGLTF.preload(ESCAVATOR_MODEL_PATH);
