/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useLayoutEffect, useMemo } from 'react';
import { useGLTF } from '@react-three/drei';
import * as THREE from 'three';

export function Escavator(props) {
    const gltf = useGLTF('/objects/escavator.glb');
    // Clone once so we can safely mutate transforms/materials
    const scene = useMemo(() => gltf.scene.clone(true), [gltf.scene]);
    const ref = useRef();

    useLayoutEffect(() => {
        // Center the model at the origin and rest it on the ground
        const box = new THREE.Box3().setFromObject(scene);
        const center = new THREE.Vector3();
        box.getCenter(center);
        scene.position.sub(center);
        scene.position.y -= box.min.y; // lift so the lowest point sits on y=0

        scene.traverse((child) => {
            if (child.isMesh) {
                child.castShadow = true;
                child.receiveShadow = true;
                if (child.material) {
                    child.material.envMapIntensity = 1;
                }
            }
        });
    }, [scene]);

    return (
        <group {...props} dispose={null} ref={ref}>
            <primitive object={scene} scale={1.8} rotation={[0, -Math.PI / 4, 0]} />
        </group>
    );
}

useGLTF.preload('/objects/escavator.glb');
