/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useLayoutEffect } from 'react'
import { useGLTF, Resize } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'

export function Escalator(props) {
    const { scene } = useGLTF('/objects/escalator.glb')
    const ref = useRef()

    // Ensure the model is centered and optimized
    useLayoutEffect(() => {
        scene.traverse((child) => {
            if (child.isMesh) {
                child.castShadow = true
                child.receiveShadow = true
                // Ensure standard material properties if needed
                if (child.material) {
                    child.material.envMapIntensity = 1
                }
            }
        })
    }, [scene])

    // Simple slow rotation if desired, otherwise static
    // useFrame(() => {
    //   if (ref.current) ref.current.rotation.y += 0.002
    // })

    return (
        <group {...props} dispose={null} ref={ref}>
            {/* Resize wrapper to normalize scale if the raw GLB is huge/tiny */}
            {/* We use a slightly different approach than generic ProductModel to ensure stability */}
            <primitive object={scene} scale={2} rotation={[0, -Math.PI / 4, 0]} />
        </group>
    )
}

useGLTF.preload('/objects/escalator.glb')
